// Captures the documentation screenshots from a freshly seeded afm-demo
// instance and regenerates docs/demo.md from the shot definitions.
//
// Usage: node capture.mjs [--bin ../../bin/afm-demo] [--root /tmp/afm-demo/dataroot]
//
// The canonical run happens inside the Playwright container (see run.sh) so the
// rendering is identical on every machine and in CI.

import { spawn } from "node:child_process";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { chromium } from "playwright";
import { shots, intro } from "./shots.mjs";

const here = path.dirname(fileURLToPath(import.meta.url));
const repo = path.resolve(here, "..", "..");

const args = parseArgs(process.argv.slice(2));
const bin = path.resolve(args.bin ?? path.join(repo, "bin", "afm-demo"));
const root = args.root ?? "/tmp/afm-demo/dataroot";
const db = args.db ?? "/tmp/afm-demo/demo.db";
const addr = args.addr ?? "127.0.0.1:8099";
const outDir = path.resolve(args.out ?? path.join(repo, "docs", "images"));
const docsFile = path.resolve(args.docs ?? path.join(repo, "docs", "demo.md"));
const baseURL = `http://${addr}`;

function parseArgs(argv) {
	const out = {};
	for (let i = 0; i < argv.length; i++) {
		if (!argv[i].startsWith("--")) continue;
		out[argv[i].slice(2)] = argv[i + 1];
		i++;
	}
	return out;
}

async function waitForServer(url, timeoutMs = 30000) {
	const deadline = Date.now() + timeoutMs;
	while (Date.now() < deadline) {
		try {
			const res = await fetch(`${url}/healthz`);
			if (res.ok) return;
		} catch {
			// not up yet
		}
		await new Promise((r) => setTimeout(r, 200));
	}
	throw new Error(`demo server did not become ready at ${url}`);
}

// Rendering tweaks that keep the output stable: no transitions, no blinking
// caret and a non-sticky header so element shots are never covered by it.
const STABLE_CSS = `
*, *::before, *::after { transition: none !important; animation: none !important; }
* { caret-color: transparent !important; }
header { position: static !important; }
`;

async function shoot(page, shot) {
	await page.goto(baseURL, { waitUntil: "networkidle" });
	await page.addStyleTag({ content: STABLE_CSS });
	await page.waitForSelector("#reviewList .card");

	const returned = await shot.prepare(page);
	// Settle any refresh the interaction triggered and drop the focus ring, so
	// repeated runs produce byte-identical images.
	await page.waitForLoadState("networkidle");
	await page.evaluate(() => {
		if (document.activeElement instanceof HTMLElement) document.activeElement.blur();
	});
	const target = shot.selector ? page.locator(shot.selector) : returned;
	await page.waitForTimeout(250);

	const file = path.join(outDir, `${shot.id}.png`);
	if (!target) {
		// Crop the empty space a short page leaves below the footer.
		const height = await page.evaluate(() => {
			const footer = document.querySelector("footer");
			return Math.ceil(footer.getBoundingClientRect().bottom + window.scrollY);
		});
		const { width } = page.viewportSize();
		await page.screenshot({ path: file, fullPage: true, clip: { x: 0, y: 0, width, height } });
		return;
	}
	const pad = shot.pad ?? 0;
	const box = await target.boundingBox();
	const scroll = await page.evaluate(() => ({ x: window.scrollX, y: window.scrollY }));
	await page.screenshot({
		path: file,
		fullPage: true,
		clip: {
			x: Math.max(0, box.x + scroll.x - pad),
			y: Math.max(0, box.y + scroll.y - pad),
			width: box.width + 2 * pad,
			height: box.height + 2 * pad,
		},
	});
}

function demoMarkdown() {
	const sections = shots
		.map((s) => `## ${s.title}\n\n${s.caption}\n\n![${s.title}](images/${s.id}.png)`)
		.join("\n\n");
	return `# Demo

<!-- Generated by tools/screenshots/capture.mjs — do not edit by hand. -->

${intro}

${sections}
`;
}

async function main() {
	await mkdir(outDir, { recursive: true });

	const server = spawn(bin, ["-addr", addr, "-root", root, "-db", db], { stdio: "inherit" });
	server.on("exit", (code) => {
		if (code !== 0 && code !== null) {
			console.error(`demo server exited with code ${code}`);
			process.exitCode = 1;
		}
	});

	let browser;
	try {
		await waitForServer(baseURL);
		browser = await chromium.launch();
		const context = await browser.newContext({
			viewport: { width: 1440, height: 900 },
			deviceScaleFactor: 2,
			locale: "en-US",
			timezoneId: "UTC",
			reducedMotion: "reduce",
		});
		// The UI is bilingual; the documentation shows the English variant.
		await context.addInitScript(() => window.localStorage.setItem("afm_lang", "en"));
		const page = await context.newPage();

		for (const shot of shots) {
			await shoot(page, shot);
			console.log(`captured ${shot.id}.png`);
		}
		await writeFile(docsFile, demoMarkdown(), "utf8");
		console.log(`wrote ${path.relative(repo, docsFile)}`);
	} finally {
		if (browser) await browser.close();
		server.kill("SIGTERM");
	}
}

await main();
